#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Jan  5 10:43:34 2018

@author: wanghaigang
"""


'''
import numpy
import matplotlib
import sklearn
from sklearn.datasets import load_boston
boston = load_boston()
print(boston.data.shape)



from sklearn.datasets import load_boston
data,target = load_boston(return_X_y=True)
print(data.shape)
print(target.shape)



from sklearn.datasets import load_iris
iris = load_iris()
print(iris.data.shape)
print(iris.target.shape)
list(iris.target_names)
'''

from sklearn.datasets import load_digits
digits = load_digits()
print(digits.data.shape)
print(digits.target.shape)
print(digits.images.shape)
import matplotlib.pyplot as plt
plt.matshow(digits.images[9])
plt.show()