#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Jan  8 11:19:56 2018

@author: wanghaigang
"""

from sklearn.neighbors import KNeighborsClassifier
X = [[0],[1],[2],[3]]
y = [0,0,1,1]


neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X,y)

print (neigh.predict([[1.1],[2.6]]))


from sklearn.datasets import load_iris

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

clf = DecisionTreeClassifier()
iris = load_iris()

cross_val_score(clf,iris.data,iris.target, cv=10)

import numpy as np
X = np.array([[-1,-1],[-2,-1],[-3,-2],[1,1],[2,1],[3,2]])
Y = np.array([1,1,1,2,2,2])
from sklearn.naive_bayes import GaussianNB

clf1 = GaussianNB(priors=None)
clf1.fit(X,Y)
print clf1.predict([[-0.9,-2]])