#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 12 14:53:48 2018

@author: wanghaigang
"""

import numpy as np
from os import listdir
from sklearn.neural_network import MLPClassifier

def img2vector(fileName):
    retMat = np.zero([1024],int)
    fr = open(fileName)
    lines = fr.readlines()
    for i in range(32):
        for j in range(32):
            retMat[i*32+j]=lines[i][j]
    return retMat

def readDataSet(path):
    filelist = listdir(path)
    numFiles = len(fileList)
    dataSet = np.zeros([numFiles,1024], int)
    hwLabels = np.zeros([numFiles,10])
    
    for i in range(numFiles):
        filePath = fileList[i]
        digit = int(filePath.split('_')[0])
        hwLabels[i][digit] = 1.0
        dataSet[i] = img2vector(path+'/'+filepath)
    return dataSet, hwLabels


train_dataSet, train_hwLabels = readDataSet('trainingDigits')


clf = MLPClassifier(hidden_layer_sizes=(100,),
                    activation='logistic',solver='adam',
                    learning_rate_init = 0.0001, max_iter=2000)


clf.fit(train_dataSet,train_hwLabels)

dataSets, hwLabels = readDataSet('testDigits')

res = clf.predict(dataSet)
