#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 12 16:28:57 2018

@author: wanghaigang

KNN手写识别实体构建

步骤1:建立工程并导入sklearn包
步骤2:加载训练数据
步骤3:构建KNN分类器
步骤4:测试集评价


"""

import numpy as np
from os import listdir
from sklearn import neighbors

def img2vector(fileName):
    retMat = np.zeros([1024],int)
    fr = open(fileName)
    lines = fr.readlines()
    for i in range(32):
        for j in range(32):
            retMat[i*32+j] = lines[i][j]
            
    return retMat


def readDataSet(path):
    fileList = listdir(path)
    numFiles = len(fileList)
    dataSet = np.zeros([numFiles,1024],int)
    hwLabels = np.zeros([numFiles])       #用于存放对应的标签（与神经网络的不同）
    for i in range(numFiles):
        filePath = fileList[i]
        digit = int(filePath.split('_')[0])
        hwLabels[i] = digit    #直接存放数字，并非one－hot向量
        dataSet[i] = img2vector(path + '/' + filepath)
    return dataSet,hwLabels


train_dataSet, train_hwLabels = readDataSet('trainingDigits')

knn = neighbors.KNeighborsClassifier(algorithm='kd_tree', n_neighbors=3)
knn.fit(train_dataSet, train_hwLabels)


dataSet,hwLabels = readDataSet('testDigits')


res = knn.predict(dataSet)
error_num = np.sum(res != hwLabels)
num = len(dataSet)

print("Total num", num, "Wrong num:")
        